name: zqyd

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1,16 * * *
 watch:
    types: started
  repository_dispatch:
    types: bean_change
jobs:
  build:

    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
        zqydbody: ${{ secrets.ZQYDBODY }}

     
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          npm install 
          npm install cron
          npm install request
      - name: '运行 【zqkkhear】'
        if: env.zqydbody
        run: |
          node zqyd.js
        env:
          zqydbody: ${{ secrets.ZQYDBODY }}
